apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediazone
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Той самий GitHub де лежить k8s-lab-app
    repoURL: https://github.com/fury2701/mediazone
    targetRevision: HEAD
    path: helm/mediazone
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mediazone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
